name: undercover_mobile
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloudinary_public: ^0.11.0
  equatable: ^2.0.3
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^4.0.1
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.1+1
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  geolocator: ^8.1.1
  get: ^4.6.1
  google_sign_in: ^5.2.3
  http: ^0.13.4
  image_picker: ^0.8.4+6
  permission_handler: ^8.3.0
  provider: ^6.0.1
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo_small.png"
  adaptive_icon_background: "assets/images/Logo_small.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/Logo_small.png
flutter_intl:
  enabled: true


flutter_native_splash:
  branding: assets/images/Logo.png
  color: "#000000"